main/urls.py
from django.urls import path
from .import views
app_name="main"
urlpatterns = [
    path('',views.home,name="home"),
    path('login/',views.login_user,name="login"),
    path('note/<int:pk>/',views.note_detail,name="note"),
    path('signup/',views.signup_user,name="signup"),
    path('logout/',views.logout_user,name="logout"),
    path('post/',views.create_post,name="post"),
    path('reset_password/',views.password_change,name="passwdchange"),
    path('search/',views.search_view,name="search"),
    path('delete/<int:pk>/',views.delete_note,name="delete"),
    path('edit/<int:pk>/',views.edit_note,name="edit"),

]

website2/urls.py
from django.contrib import admin
from django.urls import path,include
from main import urls

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    created_by=models.ForeignKey(User,on_delete=models.CASCADE)#user akiwa deleted,hadi post zake zikue deleted
    title=models.CharField(max_length=200)
    note = models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    #tuciclick posts wat will we see
    def __str__(self):
        return self.name + "/n" +  self.note
    

main/forms.py
from django import forms
from .models import Post

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,SetPasswordForm
from django.contrib.auth.models import User
 
class RegisterForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=("username","email","password1","password2")
        help_text={
            "password1":None,
            "password2":None,
        }

        username=forms.CharField(widget=forms.TextInput())
        email=forms.EmailField(widget=forms.TextInput(attrs={
            'class':'text-dark p-2 form-control ',
            'placeholder':'enter your email'
        }))

     #hi nmeadd ndi ieke stuff na placeholder  
    def __init__(self, *args, **kwargs):#field zmekua generated by the default USER form ya django
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control m-1', 'placeholder': 'enter password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control m-1', 'placeholder': 'confirm pasword'})
        self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-control m-1', 'placeholder': 'enter email'})
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control m-1', 'placeholder': ' enter username'})
        

    def save(self,commit=True):
        user=super(RegisterForm, self).save(commit=False)
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user

class AuthForm(AuthenticationForm):
    class Meta:
        model=User
        fields=("username","password")
    def __init__(self, *args, **kwargs):#field zmekua generated by the default USER form ya django
            super(AuthForm, self).__init__(*args, **kwargs)
            self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control m-1', 'placeholder': 'username'})
            self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control m-1', 'placeholder': 'password'})

#create a new form
class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=("title","note")

#recover password
class NewPassForm(SetPasswordForm):
    model=User
    fields=('new password','confirm password')

class EditNoteForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","note")
    def save(self,commit=True):
        note=super(PostForm, self).save()
        if commit:
            form.save()
        return note

main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import RegisterForm,UserCreationForm,AuthForm,PostForm,NewPassForm,EditNoteForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .models import Post
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import ValidationError
# Create your views here.
#login_required(login_url="/login")#if not logged in redirect hapa
def home(request):
    posts=Post.objects.all()
    return render(request,"main/home.html",{
        'posts':posts
    })

def signup_user(request):
    if request.method == "POST":
        form =RegisterForm(request.POST)
        
        if len(form.data.get('password1'))>0:
                if  len(form.data.get('password1'))<=7:
                    messages.error(request,"password is too short")
        elif form.data.get('password1') != form.data.get('password2'):
            messages.error(request, "passwords do not match")
            form=RegisterForm()
        else:
            if form.is_valid():
                user=form.save()
                messages.success(request,"account created,login to complete")
                login(request, user)    
                return redirect("main:home")
            
            
            messages.error(request,"invalid hence user not created")
            form=RegisterForm()
    form=RegisterForm()
    return render(request,"main/signup.html",{
        'form':form
    })

def login_user(request):
    if request.method == "POST":
        form =AuthForm(request,data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                messages.success(request, "logged in successfully")#message first then redirect
                return redirect("main:home")
            messages.error(request, "user with such credentials doesn't exist")
        messages.error(request,"invalid details")
        form=AuthForm()
    form=AuthForm()
    return render(request,"main/login.html",{
        'form':form
    })


def logout_user(request):
    logout(request)
    messages.success(request,"successfully logged out")
    return redirect("main:login")

@login_required(login_url="/login")#if not logged in redirect hapa
def create_post(request):
    if request.method == "POST":
        form=PostForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)#tusisave kwanza hadi tuadd mwenye ameicreate
            post.created_by=request.user
            post.save()
            messages.success(request, "note added successfully")
            return redirect ("main:home")
    else:
        form=PostForm()
    return render(request, "main/post.html",{
        'form':form
    })

@login_required
def password_change(request):
    user = request.user
    if request.method == "POST":
        form = NewPassForm(user,request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"password changed successfully")
            return redirect("main:login")
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
    form=NewPassForm(user)
    return render(request, 'main/newp.html', {'form': form})

def note_detail(request,pk):
    note=get_object_or_404(Post,pk=pk)
    return render(request, 'main/detail.html',{'note':note})

def search_view(request):
    query=request.GET.get('query','')
    if query:
        notes=Post.objects.filter(Q(note__contains=query)|Q(title__icontains=query))
    else:
        posts=Post.objects.all().order_by("created_at")
    return render(request, "main/search.html",{
        'query':query,
        'notes':notes
    })
def edit_note(request,pk):
        form=EditNoteForm()
        note=get_object_or_404(Post,pk=pk,created_by=request.user)
        if request.method == "POST":
            form =EditNoteForm(request.POST,instance=note)
            if form.is_valid():
                form.save()
                return redirect("main:detail",pk=note.id)
        else:
            form=EditNoteForm(instance=note)
        return render(request, "main/edit.html",{'form':form})

def delete_note(request,pk):
    post=get_object_or_404(Post,pk=pk,created_by=request.user)
    post.delete()
    return redirect("main:home")

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7e19cdda80.js" crossorigin="anonymous"></script>
    <title>{%block title%}my site{%endblock%}</title>
    <style>
        #mynav:hover{
            background-color:rgb(106, 0, 255);

        }
        .flex-container {
            display: flex;
            flex-wrap: wrap;
          }
          
          .flex-container > div {
            background-color: #f1f1f1d6;
            width: 33%%;
            margin: 10px;
            text-align: center;
            line-height: 75px;
            font-size: 20px;
          }
        form.table{
            display:inline-block;
            margin-left:auto;
            text-align:center;
        }
        
    </style>
</head>
<body class="ml-auto">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark border nav-pills" id="navvar">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav">
                <i class="fa-solid fa-house fa-bounce" style="color: hsl(218, 94%, 49%)" aria-label="pages"></i>
            </button>
            <div class="collapse navbar-collapse " id="nav">
                <div class="navbar-nav justified" >
                   
                    
                    
                    {% if user.is_authenticated %}
                    <a class="nav-link nav-item text-light rounded btn btn-outline-info" aria-current="page" href="{% url 'main:home' %}" id="mynav">Home</a>
                    
                    <a class="nav-link nav-item text-light rounded align-right" href="{% url 'main:post' %}" id="mynav">create</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="nav-link nav-item text-light rounded align-right" href="{% url 'main:passwdchange' %}" id="mynav">Change password</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {% comment %} form ya kusearch {% endcomment %}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="nav-link nav-item text-light rounded" href="{% url 'main:logout' %}" id="mynav">Logout</a>&nbsp;&nbsp;
                    <i class="fa-solid fa-circle-user fa-beat fa-lg mt-3" style="color: #eeeff2;"></i><p class="p-2 ml-4 mb-1 text-light">{{request.user}} | Logged In<p>
                    {% else %}
                    <a class="nav-link nav-item text-light rounded btn btn-outline-info" aria-current="page" href="{% url 'main:home' %}" id="mynav">Home</a>
                    <a class="nav-link nav-item text-light rounded" href="#" id="mynav">About</a>
                    <a class="nav-link nav-item text-light rounded" href="{% url 'main:signup' %}" id="mynav">Signup</a>
                    <a class="nav-link nav-item text-light rounded" href="{% url 'main:login' %}" id="mynav">Login</a>
                    {% endif %}
                    
                </div>
            </div>
        </nav>
        
    </div>
   
        {%block content%}
        {%endblock%}

    
</body>
</html>

main/templates/main/detail.html
{% extends 'main/base.html' %}
{% block title  %}home{% endblock  %}
{% block content %}
<div class="container border shadow">
    <h4>Writer :{{note.created_by}}</h4>
    <p>Title :{{note.title}}</p>
    {{note.note}}
    <hr>
    <div>
        <p>{{note.created_at}}</p>
    </div>

</div>
{%endblock%}

main/templates/main/edit.html
{% extends 'main/base.html' %}
{% block title  %}POST{% endblock  %}
{% block content %}
{% if messages %}{% for message in messages  %}
<div class="alert dismissible fade show bg-info mt-2 ml-auto p-1 ">
{{message}}
<button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
</div>
{% endfor %}{% endif %}
<div class="container center "> 
<form action="." method="POST">
    {% csrf_token %}
    <table>
    <tr>
    <td>Title:{{form.title}}</td>
    </tr>
    
    <tr>
    <td>Note:{{form.note}}</td>
    </tr>
    </table>
    <button type="submit" class="btn btn-outline-primary" aria-label="submit">Done</button>
    
        {% if form.errors%}
        <div class="alert bg-warning" role="alert" >
        {% for error in form.field %}
            {{error}}
            <button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
        {% endfor %}
        </div>
        {% endif %}
    
</form>
</div>
{% endblock  %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title  %}home{% endblock  %}
{% block content %}
<form method="GET" action="{% url 'main:search'%}" class=" m-2">
    <input type="text" name="query" value="{{query}}" class="text-dark">
    <button type="submit" class="btn btn-outline-info " placeholder="search by title or writer">search</button>
</form>
<hr>
<div class="flex-container">
    {% for post in posts  %}
        <div class="card m-2">
            <div class="card-header">{{post.created_by.username}} @{{post.created_at}}</div>
            <div class="card-body ">
                    <p>Title:{{post.title}}</p>
                    {% if request.user == post.created_by %}<a href="{% url 'main:delete' post.id %}"><button class="btn btn-outline-danger m-2">Delete</button></a>
                    <a href="{% url 'main:edit' post.id %}"><button class="btn btn-outline-success m-2">Edit</button></a>{% endif %}
                    
                    <a href="{% url 'main:note' post.id%}"><button class="btn btn-outline-success">read more</button></a>
            </div>
        </div>{%empty%}<p>No posts Yet :(</p>
{% endfor %}
</div>
{% endblock  %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block title  %}signup{% endblock  %}
{% block content %}
{% if messages %}{% for message in messages  %}
<div class="alert dismissible fade show bg-info mt-2 ml-auto p-1 ">
{{message}}
<button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
</div>
{% endfor %}{% endif %}
<div class="container center "> 
<form action="." method="POST">
    {% csrf_token %}
    <table>
    {{form.as_t}}
    <tr>
    <td>{{form.username}}</td>
    </tr>
    
    <tr>
    <td>{{form.password}}</td>
    </tr>
    </table>
    <button type="submit" class="btn btn-outline-primary" aria-label="submit">Done</button>
    
        {% if form.errors%}
        <div class="alert bg-warning" role="alert" >
        {% for error in form.field %}
            {{error}}
            <button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
        {% endfor %}
        </div>
        {% endif %}
    
</form>
</div>
{% endblock  %}

main/templates/main/newp.html
{% load crispy_forms_tags %}
{% block content %}
{% if messages %}
{% for message in messages  %}
{{message}}
{% endfor %}
{% endif %}
{% if errors %}
{% for error in errors  %}
{{error}}{% endfor %}
{% endif %}
    <div class="content-section">
        
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-info" type="submit">Reset password</button>
        </form>
    </div>
{% endblock %}

main/templates/main/post.html
{% extends 'main/base.html' %}
{% block title  %}POST{% endblock  %}
{% block content %}
{% if messages %}{% for message in messages  %}
<div class="alert dismissible fade show bg-info mt-2 ml-auto p-1 ">
{{message}}
<button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
</div>
{% endfor %}{% endif %}
<div class="container center "> 
<form action="." method="POST">
    {% csrf_token %}
    <table>
    <tr>
    <td>Title:{{form.title}}</td>
    </tr>
    
    <tr>
    <td>Note:{{form.note}}</td>
    </tr>
    </table>
    <button type="submit" class="btn btn-outline-primary" aria-label="submit">Done</button>
    
        {% if form.errors%}
        <div class="alert bg-warning" role="alert" >
        {% for error in form.field %}
            {{error}}
            <button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
        {% endfor %}
        </div>
        {% endif %}
    
</form>
</div>
{% endblock  %}

main/templates/main/search.html
{% extends 'main/base.html' %}
{% block title  %}home{% endblock  %}
{% block content %}
<form method="GET" action="{% url 'main:search'%}" class="bg-light m-2">
    <input type="text" name="query" value="{{query}} " class="text-dark" placeholder="search by title or writer">
    <button type="submit" class="btn btn-outline-info " >search</button>
</form>
<hr>
<div class="flex-container m-2">
    {% for post in notes  %}
        <div class="card m-2">
            <div class="card-header">{{post.created_by}} </div>
            <div class="card-body ">
                    <p>{{post.note}}</p>
            </div>
        </div>{%empty%}<p>Note Yet :(</p>
{% endfor %}
</div>
{% endblock  %}

main/templates/main/signup.html
{% extends 'main/base.html' %}
{% block title  %}signup{% endblock  %}
{% block content %}
{% if messages %}{% for message in messages  %}
<div class="alert dismissible fade show bg-info mt-2 ml-auto p-1 ">
{{message}}
<button type="button" data-bs-dismiss="alert" class="btn-close" aria-label="close"></button>
</div>
{% endfor %}{% endif %}
<div class="justify-content"> 
<form action="." method="POST" class="center">
    {% csrf_token %}
    <table class="">
    
    <tr>
    <td >{{form.username}}</td>
    </tr>

    <tr>
    <td>{{form.email}}</td>
    </tr>

    <tr>
    <td>{{form.password1}}</td>
    </tr>

    <tr>
    <td>{{form.password2}}</td>
    </tr></tr>
    <tr><td><button type="submit" class=" btn btn-outline-primary" aria-label="submit">Done</button></td></tr>
    </table>
    
    
        {% if form.errors%}
        <div class="alert bg-warning" role="alert" >
        {% for error in form.field %}
            {{error}}
            <button type="button" data-bs-dismiss="alert" class="btn-close ml-auto" aria-label="close"></button>
        {% endfor %}
        </div>
        {% endif %}
    
</form>
</div>
{% endblock  %}